name: test
on: [push]
jobs:
  tests-docker:
    name: docker-jdk13
    runs:
      using: 'docker'
      image: 'Dockerfile'
    args:
      - -PinParallel=true

  tests:
    name: test ${{ matrix.os }} - Java${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [ 9, 10, 11, 12, 13 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set up Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install gauge
        run: npm i -g @getgauge/cli
      - name: test
        if: matrix.os != 'windows-latest'
        run: ./gradlew gauge

  tests-windows:
    name: test windows - Java${{ matrix.java }}
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 9, 10, 11, 12, 13 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: install gauge
        run: |
          choco install gauge
          echo "::add-path::C:\\Program Files\\gauge\\bin"
      - name: test
        run: ./gradlew gauge