name: test
on: [push]
jobs:
  tests:
    name: test ${{ matrix.os }} - {{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [ 8, 9, 10, 11, 12, 13 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set up Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install gauge
        run: npm i -g @getgauge/cli
      - name: test
        if: matrix.os != 'windows-latest'
        run: ./gradlew clean gauge

  tests-windows:
    name: test windows - {{ matrix.java }}
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 8, 9, 10, 11, 12, 13 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: install gauge
        run: choco install gauge --version=1.0.7
      - name: test
        run: |
          gauge.exe install java
          ./gradlew clean gauge